services:
  dns:
    build: ./DNS-Server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    secrets:
      - db_password
  web:
    build: ./dream-server
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - saves:/saves
volumes:
    db:
      driver: local
    saves:
      driver: local
secrets:
    db_password:
      file: db_password.txt
