services:
  web:
    build: ./dream-server
    ports:
      - "80:80"
  dns:
    build: ./DNS-Server
    ports:
      - "53:53"
  redis:
    image: "redis:alpine"
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
    db:
      - driver: local
